### PR TITLE
[WIP]fix travis nodejs heap oom

### PR DESCRIPTION
**Pull request by yshing**

### CODE REVIEW

**Comment by nandiheath** [comment]
will this fix the oom? or should set the `max_old_space_size` instead?

**Review by nandiheath — CHANGES_REQUESTED** [review]
`max_old_space_size` instead?

**Comment by yshing** [comment]
Setting max_old_space_size to a fix number can be much trickier for 2 reason:
1. Need to make sure the flag pass the flag all the way down.
2. The available memory size might not be exactly the same for each run.

Hence, it'd be better use node 12, let it determine the maximum memory it can use at runtime.

And I don't know how much memory it's available inside that Travis VM LoL...

**Comment by tonyhhyip** [comment]
I prefer to use Node.js 12 as it would provide performance improvement as well

**Comment by nandiheath** [comment]
ok got it!

**Pull request merged**
