### PR TITLE
feat: use css instead of react-responsive

### PR DESCRIPTION
**Pull request by tonyhhyip**
* **Please check if the PR fulfills these requirements**
- [x] The commit message follows our guidelines
- [ ] i18n translation has been added / updated (for bug fixes / features)

* **What kind of change does this PR introduce?** (Bug fix, feature, docs update, ..., provide screenshots if necessary)
Use css instead of react-responsive.
Performance improvement depends on browser engine.
CSS is handled by browser while react responsive is handled with js engine which has overhead

* **Does this PR introduce a breaking change?** (What changes might users need to make in their application due to this PR?)

* **Other information**:

### CODE REVIEW

**Comment by nandiheath** [comment]
possible to remove `react-responsive` from `package.json` as well?

**Comment by tonyhhyip** [comment]
no, because more than one page is using react responsive

**Comment by tonyhhyip** [comment]
@nandiheath Just try to remove however it is used with the chart (c3), so I can't remove it currently

**Comment by nandiheath** [comment]
this was outdated. re-open this if necessary

**Pull request closed without merging**
